---
title: 'Test links in kable documents'
author: "Quentin D. Read"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(kableExtra)

mylinks <- c('http://quentinread.com', 'https://cyberhelp.sesync.org')

dat <- data.frame(x = 1:4,
                  stuff = c('floo', paste0('\\href{', mylinks, '}{some stuff}'), 'This is cool \\href{google.com}{dude}'),
                  y = rep('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 4),
                  w = rep('floooooooooooooooooooooooo oooooooooooooooooooooooooooodle', 4))

dat <- do.call(rbind, replicate(100, dat, simplify = FALSE))

kbl(dat, booktabs = TRUE, escape = FALSE, longtable = TRUE) %>%
  pack_rows("Things", 1, 10, background = "#D4EBF2") %>%
  column_spec(1, width = '7em') %>%
  column_spec(2, width = '7em') %>%
  column_spec(3, width = '7em') %>%
  column_spec(4, width = '7em') %>%
  kable_styling(font_size = 6, latex_options = c('repeat_header'))

```

